name: halloy
version: "2024.14"
summary: IRC application written in Rust
description: |
  Halloy is an open-source IRC client written in Rust, with the Iced
  GUI library. It aims to provide a simple and fast client for Mac, 
  Windows, and Linux platforms.

grade: stable
confinement: strict
base: core22
compression: lzo

icon: snap/gui/org.squidowl.halloy.png
website: https://squidowl.org/
source-code: https://github.com/squidowl/halloy
issues: https://github.com/squidowl/halloy/issues
contact: https://github.com/squidowl/halloy/issues

architectures:
  - build-on: amd64
  - build-on: arm64
  - build-on: armhf

parts:
  alsa-mixin:
    plugin: dump
    source: https://github.com/diddlesnaps/snapcraft-alsa.git
    source-subdir: snapcraft-assets
    build-packages:
      - libasound2-dev
    stage-packages:
      - libasound2
      - libasound2-plugins
  halloy:
    after: [alsa-mixin]
    plugin: rust
    source: https://github.com/squidowl/halloy/archive/refs/tags/$SNAPCRAFT_PROJECT_VERSION.tar.gz
    override-build: |
      craftctl default
      install -Dm644 $CRAFT_PART_SRC/assets/linux/org.squidowl.halloy.appdata.xml $CRAFT_PART_INSTALL/share/metainfo/org.squidowl.halloy.appdata.xml
    build-packages:
      - cargo
      - libssl-dev
      - libasound2-dev
      - pkg-config
      - libpulse-dev
    stage-packages:
      - libxkbcommon-x11-0
      - libpulse0
    parse-info: [share/metainfo/org.squidowl.halloy.appdata.xml]
  launcher:
    source: snap/local
    plugin: dump

apps:
  halloy:
    environment:
      LD_LIBRARY_PATH: "$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/pulseaudio:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/"
      LC_ALL: "C.UTF-8"
      ALWAYS_USE_PULSEAUDIO: '1'
      ALSA_CONFIG_PATH: /snap/$SNAPCRAFT_PROJECT_NAME/current/usr/share/alsa
    command: bin/launch
    common-id: org.squidowl.halloy
    extensions: [gnome]
    plugs:
      - network
      - audio-playback
